#!/usr/bin/env bash
set -euo pipefail
SCDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCDIR/../.." && pwd)"
cd "$REPO"
BASE="Qwen/Qwen2.5-3B-Instruct"
OUT="outputs"
echo "[1/5] merge SFT adapter"
python -m training.reasoning.merge --base "$BASE" --adapter "$OUT/reasoning-sft" --output "$OUT/reasoning-sft-merged"
echo "[2/5] GRPO RL on merged SFT"
python -m training.reasoning.train_grpo --base "$OUT/reasoning-sft-merged" --gens 8 --batch 2 --max-completion 768
GRPO_CKPT="$(ls -d "$SCDIR/$OUT/reasoning-grpo"/checkpoint-* 2>/dev/null | sort -V | tail -1)"
test -n "$GRPO_CKPT"
echo "[3/5] merge GRPO ($GRPO_CKPT)"
python -m training.reasoning.merge --base "$OUT/reasoning-sft-merged" --adapter "$GRPO_CKPT" --output "$OUT/reasoning-grpo-merged"
echo "[4/5] GSM8K evals (base/SFT/GRPO)"
python -m training.reasoning.eval_judge --model "$BASE" --limit 100 --output "data/eval_base.json"
python -m training.reasoning.eval_judge --model "$OUT/reasoning-sft-merged" --limit 100 --output "data/eval_sft.json"
python -m training.reasoning.eval_judge --model "$OUT/reasoning-grpo-merged" --limit 100 --output "data/eval_grpo.json"
echo "[5/5] MATH-500 evals (base/SFT/GRPO)"
python -m training.reasoning.eval_judge --model "$BASE" --dataset HuggingFaceH4/MATH-500 --limit 100 --output "data/eval_base_math.json"
python -m training.reasoning.eval_judge --model "$OUT/reasoning-sft-merged" --dataset HuggingFaceH4/MATH-500 --limit 100 --output "data/eval_sft_math.json"
python -m training.reasoning.eval_judge --model "$OUT/reasoning-grpo-merged" --dataset HuggingFaceH4/MATH-500 --limit 100 --output "data/eval_grpo_math.json"
echo "ALL DONE"